language: csharp
os:
    - linux
    - osx

# OS-X поддерживать некому
matrix:
    allow_failures:
        os: osx

dotnet: 2.0.0
solution: src/1Script_Mono.sln
install:
    - dotnet restore ${TRAVIS_SOLUTION} /p:Configuration=Release /p:Platform=x86
    - nuget restore ${TRAVIS_SOLUTION} /p:Configuration=Release /p:Platform=x86
script:
    - install/build.sh /p:Platfrom="x86"
    - echo "lib.system=${PWD}/oscript-library/src" > src/oscript/bin/Release/net452/oscript.cfg
    - ./travis-runtests.sh src/oscript/bin/Release/net452
